## Numpy

In [70]:
# Load in Numpy
import numpy as np

## The Basics

In [71]:
a= np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [72]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [73]:
#Get dimention
a.ndim

1

In [74]:
# Get shape
a.shape

(3,)

In [75]:
b.shape

(2, 3)

In [76]:
# Get type
a.dtype

dtype('int16')

In [77]:
b.dtype

dtype('float64')

In [78]:
# Get size
a.itemsize

2

In [79]:
# Get total size
a.nbytes

6

### Accessing/changing specific elements, rows,columns

In [80]:
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [81]:
# Get specific element [r,c]
a[1,5]

13

In [82]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [83]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [84]:
# [startindex: endindex: stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [85]:
# Change elements
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [86]:
# 3-d example
b=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [87]:
# To get specific element, work outside in
b[0,1,1]

4

In [88]:
# To replace
b[:,1,:]= [[9,9,9],[8,8]]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
b

### Initializing Different Types of Arrays

In [ ]:
# All zeros matrix
np.zeros((2,3))

In [ ]:
# All ones
np.ones((4,2,2))

In [ ]:
# Any other number
np.full((2,2),99)

In [ ]:
# Any other number (full like)
np.full_like(a,4)

In [ ]:
np.full(a.shape,4)

In [ ]:
# Random decimal numbers
np.random.rand(4,2)

In [ ]:
# Random integer values
np.random.randint(4,7, size=(3,3))

In [ ]:
# Identity matrix
np.identity(3)

In [ ]:
# Repeat an array
arr=np.array([(1,2,3)])
r1=np.repeat(arr,3, axis=0)
print(r1)

In [ ]:
# Exercise
output= np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4]=z
print(output)

In [ ]:
# When coppying arrays
a= np.array([1,2,3])
b=a.copy()
b[0]=100

print(a)

### Mathematics

In [ ]:
a= np.array([1,2,3,4])
print(a)

In [ ]:
a+2

In [ ]:
a-2

In [ ]:
b=np.array([1,0,1,0])
a+b

In [ ]:
a**2

In [ ]:
# Take the sin
np.sin(a)

### Linear Algebra

In [ ]:
# Matrix multiplication
a= np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

np.matmul(a,b)

In [ ]:
# Find the determinant
c= np.identity(3)
np.linalg.det(c)

### Statistics

In [ ]:
stats= np.array([[1,2,3],[4,5,6]])
stats

In [ ]:
np.min(stats, axis=0)

In [ ]:
np.max(stats)

In [ ]:
np.sum(stats)

### Reorganizing Arrays

In [ ]:
before= np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after= before.reshape((4,2))
print(after)

In [ ]:
# Vertically stacking vectors
v1= np.array([1,2,3,4])
v2= np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

In [ ]:
# Horizontal stack
h1= np.ones((2,4))
h2= np.zeros((2,2))

np.hstack([h1,h2])

### Miscellaneous

#### Boolean Masking and Advanced Indexing

In [ ]:
# Indexing with a list
a= np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]
333

In [ ]:
np.any(b>2, axis=0)