## NumPy

### Creating NumPy Arrays

In [2]:
# Using array() method
import numpy as np
nums_list=[10,12,14,16,20]
nums_array= np.array(nums_list)
type(nums_array)

numpy.ndarray

In [3]:
# Creating multi-dimensional NumPy arrays
row1=[10,12,13]
row2=[45,32,16]
row3=[45,32,16]

nums_2d=np.array([row1,row2,row3])
nums_2d.shape

(3, 3)

In [4]:
# Using arrange() method
nums_arr=np.arange(5,11)
print(nums_arr)

[ 5  6  7  8  9 10]


In [5]:
# Using Ones Method
ones_array=np.ones(6)
print(ones_array)

[1. 1. 1. 1. 1. 1.]


In [6]:
# 2-d array of ones
ones_array=np.ones((6,4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
# Using Zeros Method
zeros_array=np.zeros(6)
print(zeros_array)

[0. 0. 0. 0. 0. 0.]


In [8]:
zeros_array=np.zeros((6,4))
print(zeros_array)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
# Using eye() method to create an identity matrix in
 #the form of a 2-d numPy array
eyes_array=np.eye(5)
print(eyes_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
# Using Random Method for an array with uniform distribution
uniform_random=np.random.rand(4,5)
print(uniform_random)

[[0.66229344 0.24103164 0.7910208  0.1308063  0.80009812]
 [0.77212125 0.15997279 0.13546627 0.73560246 0.27155859]
 [0.53290284 0.96546748 0.10615759 0.5862926  0.8007359 ]
 [0.28183619 0.16317773 0.61228842 0.33497034 0.68573733]]


In [12]:
# Using random.randn() for an array with uniform distribution
uniform_random=np.random.randn(4,5)
print(uniform_random)

[[ 2.62141052 -0.34537122 -0.51387294  0.55949946  1.72194613]
 [ 0.16686398 -1.64635309  0.23625254 -2.13733976  0.27015568]
 [ 0.65346187  2.04724549  0.77075984  0.17340229  0.79567943]
 [ 0.70363887  0.39763399 -0.75502367 -1.01692358 -0.30729311]]


In [13]:
# random.randint() creates an array with random 
 #integers between a certain range.
integer_random=np.random.randint(10,50,5)
print(integer_random)

[20 28 26 20 37]


In [15]:
# To reshape numPy array
uniform_random.reshape(5,4)

array([[ 2.62141052, -0.34537122, -0.51387294,  0.55949946],
       [ 1.72194613,  0.16686398, -1.64635309,  0.23625254],
       [-2.13733976,  0.27015568,  0.65346187,  2.04724549],
       [ 0.77075984,  0.17340229,  0.79567943,  0.70363887],
       [ 0.39763399, -0.75502367, -1.01692358, -0.30729311]])

### Array Indexing and Slicing

In [16]:
# Slicing means dividing an array into multiple parts

In [18]:
# Accessing item by index
s=np.arange(1,11)
print(s)
print(s[1])

[ 1  2  3  4  5  6  7  8  9 10]
2


In [19]:
# Slicing
print(s[1:9])

[2 3 4 5 6 7 8 9]


In [20]:
# To specify upper and lower bounds
print(s[:5])
print(s[5:])

[1 2 3 4 5]
[ 6  7  8  9 10]


In [22]:
# Slicing on 2-dimensional array
 # Apply slicing on arrays and columns seperately
row1=[10,12,13]
row2=[45,32,16]
row3=[45,32,16]

nums_2d=np.array([row1,row2,row3])
print(nums_2d[:2,:])

[[10 12 13]
 [45 32 16]]


In [23]:
nums_2d=np.array([row1,row2,row3])
print(nums_2d[:,:2])

[[10 12]
 [45 32]
 [45 32]]


### NumPy for Arithmetic |Operations

In [24]:
# Finding square roots
nums=[10,20,30,40,50]
np_sqr=np.sqrt(nums)
print(np_sqr)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [25]:
# Logarithm
np_log=np.log(nums)
print(np_log)

[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


In [26]:
# Exponent
np_exp=np.exp(nums)
print(np_exp)

[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]


### NumPy for Linear Algebra Operations

In [27]:
# Matrix Dot Product with the dot() function
a=np.random.randn(4,5)
b=np.random.randn(5,4)

z=np.dot(a,b)

print(z)

[[-2.72971748  1.78099695  2.12450369  0.10247833]
 [ 0.34397437 -0.15587059 -1.21751466 -0.69179763]
 [-2.02912912  0.26675115  0.53487584  1.32032753]
 [-2.15219834  1.21072176  1.94803178  0.42977823]]


In [28]:
# Element-wise Matrix Multiplication with the multiply() function
nums_2d=np.array([row1,row2,row3])
multiply=np.multiply(nums_2d,nums_2d)
print(multiply)

[[ 100  144  169]
 [2025 1024  256]
 [2025 1024  256]]


In [30]:
# Matrix Inverse with the linalg.inv() function
row1=[1,2,3]
row2=[4,5,6]
row3=[7,8,9]

nums_2d=np.array([row1,row2,row3])
inverse=np.linalg.inv(nums_2d)
print(inverse)

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [31]:
#Matrix Determinant with the linalg.det() function
determinant=np.linalg.det(nums_2d)
print(determinant)

-9.51619735392994e-16


In [34]:
# Matrix trace with the trace() function
trace=np.trace(nums_2d)
print(trace)

15
