### Numpy

In [11]:
#We import a library using import keyword
import numpy as np
import math

### Array creation

In [12]:
# Arrays are displayed as lists or lists of lists
#In arrays, we pass in a list as an argument
a= np.array([1,2,3])
print(a)
#We can print the numbers of dimensions of a list
print(a.ndim)

[1 2 3]
1


In [13]:
#To pass in a list of list, create a multidimensional array, like a matrix
b= np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
# To print the length of each dimension
b.shape

(2, 3)

In [15]:
# Type of items in array
a.dtype

dtype('int32')

In [16]:
#Floats are also accepted
c= np.array([2.2, 5, 1.1])
c.dtype.name

'float64'

In [17]:
c

array([2.2, 5. , 1.1])

In [18]:
# Two arrays, different filler values but same shape
d=np.zeros((2,3))
print(d)

e=np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# We can generate an array with random numbers
np.random.rand(2,3)

array([[0.57459595, 0.35418937, 0.1980059 ],
       [0.23731077, 0.14902886, 0.52143843]])

In [20]:
# Array of every even number from ten to fifty
f= np.arange(10, 50, 2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [21]:
# Sequence of floats
np.linspace(0,2,15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

## Array Operations

In [22]:
# Arithmetic operators on arrays only apply elementwise
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])

c=a-b
print(c)

d=a*b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [23]:
# Array of farenheit values
farenheit = np.array([0,-10,-5,-15,0])

# Formula for conversion is ((F-32)* 5/9= C)
celcius= (farenheit - 31)*(5/9)
celcius

array([-17.22222222, -22.77777778, -20.        , -25.55555556,
       -17.22222222])

In [24]:
# Apply operator on array to get boolean values
celcius> -20

array([ True, False, False, False,  True])

In [25]:
# Elementwise product uses the "*" sign
a= np.array([[1,1],[0,1]])
b= np.array([[2,0],[3,4]])
print(a*b)

[[2 0]
 [0 4]]


In [26]:
# For matrix product, use "@" sign or dot function
print(a@b)

[[5 4]
 [3 4]]


In [27]:
#To see the shape of matrix
a.shape

(2, 2)

In [28]:
# When manipulating arrays of different types, the type of the resulting array will 
#correspond to the more general of the two. This is called upcasting
array1= np.array([[1,2,3],[4,5,6]])
print(array1.dtype)

array2= np.array([[7.1,8.2,9.1],[10.4,11.2,12.3]])
print(array2.dtype)

# Number after the type represents the number of bits the operating system reserves.

int32
float64


In [29]:
# Items in the resulting array will be upcast into floating point numbers
array3= array1+array2
print(array3)
print(array3.dtype)

[[ 8.1 10.2 12.1]
 [14.4 16.2 18.3]]
float64


In [30]:
# Numpy arrays have other functions
print(array3.sum())
print(array3.max())
print(array3.min())
print(array3.mean())

79.3
18.3
8.1
13.216666666666667


## Two dimensional arrays

In [31]:
b= np.arange(1,16,1).reshape(3,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [32]:
# Using python imaging library (pil) to display images
from PIL import Image
from IPython.display import display

im= Image.open('Screenshot(1).tiff')
display(Im)

FileNotFoundError: [Errno 2] No such file or directory: 'Screenshot(1).tiff'

## Indexing, Slicing and Iterating

### Indexing

In [ ]:
# For 1-d array, use offset index
a= np.array([1,3,5,7])
a[2]

In [ ]:
# For multidimensional arrays, use integer array indexing
a=np.array([[1,2],[3,4],[5,6]])
a

In [ ]:
# To select one element, enter the index. 
#The first integer is the row. The second is the column
a[1,1]

In [ ]:
# To get multiple elements, enter indicies into an array function
np.array([a[0,0], a[1,1], a[2,1]])

In [ ]:
# Or...
print(a[[0,1,2],[0,1,1]])

### Boolean Indexing

In [ ]:
# Allows us select arbitrary elements based on conditions
print(a>5)

In [ ]:
# mask array over oringinal to return a 1-d array relating to the true values
print(a[a>5])

### Slicing

In [ ]:
# Slicing is a way to create a sub-array based on the original array.
# Works for 1-d similar to a list
a= np.array([0,1,2,3,4,5])
print(a[:3])

In [ ]:
# For multi-dimentional arrays
a=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

In [ ]:
a[:2]

In [ ]:
a[:2, 1:3]

In [ ]:
sub_array= a[:2, 1:3]
print('Sub array index [0,0] value before change:', sub_array[0,0])
sub_array[0,0]= 50
print('Sub array index [0,0] value after change:', sub_array[0,0])
print('oringinal array index [0,1] value after change:', a[0,1])